### ISSUE TITLE
Wrong link of VG-DR-Net dataset

### ISSUE THREAD

**Issue by wangxinyu0922** [yikang-li/FactorizableNet#1]
Hi, thank you for your great code.
The download link of  VG-MSDN, VG-DR-Net are the same and point to the vg_msdn.tgz file, could you check it please?

Further more:
In part: Evaluation with our Pretrained Models
CUDA_VISIBLE_DEVICES=0 python train_FN.py --evaluate --dataset_option=normal \
	--path_opt options/models/VG-MSDN.yaml \
	--pretrained_model output/trained_models/Model-VG-MDSN.h5

The pretrained model name is Model-VG-M**SD**N.h5 but not Model-VG-M**DS**N.h5 ...
And the results of VG-DR-Net is the same as the VG-MSDN and is different from the paper.

**Comment by yikang-li** [comment]
Hi xinyu, 

Thanks for your reminding! 

We really apologize for the wrong link of Model-VG-DR-Net. We may mistakenly delete the previous model. I will re-train a model and update the link within one week. 

Best,
Yikang

**Comment by wangxinyu0922** [comment]
@yikang-li Well, I think it is the problem of **Dataset** VG-DR-Net, but not the model?

**Comment by yikang-li** [comment]
@wangxinyu0922 Thanks for reminding! I also found the model link was also broken. Both have been solved. 

Best,
Yikang
