### ISSUE TITLE
How many epochs are necessary?

### ISSUE THREAD

**Issue by sairin1202** [yikang-li/FactorizableNet#11]
epoch0
 Top-50 Recall:  [Pred] 11.864%  [Phr] 9.651%    [Rel] 4.358%
 Top-100 Recall: [Pred] 15.013%  [Phr] 12.640%   [Rel] 5.590%

epoch1
 Top-50 Recall:  [Pred] 11.905%  [Phr] 11.497%   [Rel] 5.128%
 Top-100 Recall: [Pred] 15.273%  [Phr] 14.760%   [Rel] 6.507%

Train with  VG-MSDN dataset from scratch.
I am wondering that to achieve the best model, how many epochs should I train?

Best regards

**Comment by yikang-li** [comment]
As I told in README.md, I usually train the model with the default config. Then using "--resume" to train 10 epochs or more. From my experience, 30 epochs are enough to get comparable results.

**Comment by cao-nv** [comment]
Sorry for replying in a closed issue, but how long did it take you to train the RPN and the full network with the batch size 1?
I'm training the full network in multi GPUs (8 Titan Xp), then I found that the batch time is too long 3.94s. With this batch time and your normal training set on Visual Genome, it takes me about 6 hours to complete an epoch. Is that training time normal? 
Looking forward to hearing from you soon.
