### ISSUE TITLE
Inconsistent VRD dataset size

### ISSUE THREAD

**Issue by oibook13** [yikang-li/FactorizableNet#13]
Thanks for the generous code release! 

I have a quick question, as mentioned in README.md, you converted original annotations into json files. For VRD, it should have 4000 training images and 1000 test images. However, in the provided json files, there are 3780 training images and 955 test images. May I know why there is such a discrepancy?

Thanks!

**Comment by yikang-li** [comment]
Hi, we clean the dataset and remove the images with no relations. I will double check the dataset.
