### ISSUE TITLE
Sharing an environment

### ISSUE THREAD

**Issue by StrangeTcy** [yikang-li/FactorizableNet#14]
Would you mind sharing the conda environment that the current code from the master branch works with?
That is, could you provide a link to a `env.yml` file?

**Comment by tejas-gokhale** [comment]
Yes this will be helpful. There are multiple compatibility issues as you seem to be using older versions of pytorch, and maybe even python 2.7.

I am not able to run the code, or even pass command line arguments

**Comment by tejas-gokhale** [comment]
Same goes for the MSDN code

**Comment by yikang-li** [comment]
The newest version of F-Net has supported pytorch 1.0. Can you have a try?

**Comment by yikang-li** [comment]
Have you pull the latest codes? we have updated the code to support multi-GPU and pytorch 1.0
