### ISSUE TITLE
Question about results without re-training

### ISSUE THREAD

**Issue by dorarad** [yikang-li/FactorizableNet#16]
Hi, thanks a lot for sharing this repository, it looks really awesome! 

What is the degree of improvement in scores before re-training end-to-end of the whole model (i.e. after training on the rpn and features? in stage 2?)
(I'm considering using your model with fixed extracted features from another detector so was wondering about that).

In particular I'm interested most in results on visual genome graph detection/generation.

Thanks a lot!

**Comment by yikang-li** [comment]
Hi, thanks for your interest in our works. 

Maybe you can have a try. We don't have that detailed number now. But re-training with '--resume' really works.

**Comment by dorarad** [comment]
I believe I won't be able to use the resume because I have a fixed features file rather than the pytorch detector model that I can use

**Comment by yikang-li** [comment]
It is easy to use fixed extracted features but the performance is not guaranteed.
