### ISSUE TITLE
How to interpret evaluation results

### ISSUE THREAD

**Issue by berthyf96** [yikang-li/FactorizableNet#17]
After running the evaluation script, I have the result `testing_result.pkl`, but I'm unsure how to interpret the annotations. For example, printing `result[0]['relationships']` shows:

```
[(25, 88, 4, 0.052851997),
 (29, 25, 10, 0.052471865),
 (29, 51, 10, 0.040551774),
 (7, 25, 10, 0.038298395),
 (3, 25, 10, 0.036385886),
 (29, 74, 8, 0.035008814),
...]
```
I assumed that the fourth value in each tuple is the confidence of that detected relationship. But then I found that there are no relationships above threshold=0.5. How can I decode these values such that I can deduce tuples of the form `(subject_class, object_class, predicate_class)` for every image?

P.S. I tried looking at `visualize_graph.py` to figure this out but found it unnecessarily complicated for what I'm trying to do. I don't need to visualize a scene graph; I just want to decode the relationships in each image.

**Comment by yikang-li** [comment]
For the details of the dumped results, I highly recommend you to have a deep look at the code. All the codes are open-sourced.  I think the probability is the prob of predicate times the subject as well as the object. You can check the detailed code for more information.

**Comment by PRYUS** [comment]
@berthyf96 Hey! Were you able to run visualize_graph.py ? I am not able to run it. Please let me know if you could.
