### ISSUE TITLE
Link error for the pretrained RPN for Visual Genome

### ISSUE THREAD

**Issue by agomezgaray** [yikang-li/FactorizableNet#2]
Than you for your excellent code. I found today and when I try to download have a problem: 

Can you review the link to the pretrained RPN for Visual Genome? Now I get the same file VRD.tgz for the VRD dataset.

Best regards.

**Comment by agomezgaray** [comment]
As a complement, the second link to the RPN.h5 is ok, but the first one (before the folders' structure and evaluation) have the VRD.tgz.

Thank you again for this excellent code.

Best regards.

**Comment by yikang-li** [comment]
I have updated the link for the first one. Thanks for your kind reminding! 

Best,
Yikang
