### ISSUE TITLE
Scripts to generate *.json files

### ISSUE THREAD

**Issue by thaolmk54** [yikang-li/FactorizableNet#21]
Hi,

Thank you for the code.

Can you please provide the scripts you used for preparing train.json/test.json so people can use your models on custom data?
 
Regards,

**Comment by PRYUS** [comment]
Hey @thaolmk54 !
We have also been looking into how to train this model on an external dataset, and I was hoping to get some help regarding this. Have you been able to run it on a custom dataset?

**Comment by yikang-li** [comment]
You can check our JSON file and make your custom data fit that. Then it will work fine. For more details, you can check the dataloader.
