### ISSUE TITLE
cuda out of memory while testing

### ISSUE THREAD

**Issue by Freya-Cui** [yikang-li/FactorizableNet#22]
Hello, I'm trying to test using the pretrained model, but the error appeared after testing 1000 images, and my GPU has 10986MiB memory:
`RuntimeError: CUDA out of memory. Tried to allocate 957.12 MiB (GPU 0; 10.73 GiB total capacity; 8.16 GiB already allocated; 801.19 MiB free; 865.05 MiB cached)`
How could I solve this problem? How much memory needed for testing?

**Comment by PRYUS** [comment]
Hey @Freya-Cui !
Could you resolve the issue? I have the same issue

**Comment by digbose92** [comment]
@Freya-Cui  were you able to solve the cuda out of memory issue ?

**Comment by muraliadithya** [comment]
@Freya-Cui Where did you add the 'with torch.no_grad()' ? Could you tell me the file name and the line number?
