### ISSUE TITLE
Using factorizable_net_v4.py forward_evaluate() to evaluate unannotated images

### ISSUE THREAD

**Issue by Hastyrush** [yikang-li/FactorizableNet#29]
Hi, great work on the project! Just wanted to ask if it is possible to run the network on unannotated raw images without loading the annotated.json file,

It seems that under your factorizable_net_v4.py there is a function forward_evaluate() to generate object names, ROIs, predicates... etc. So I'm assuming that I can use this function to evaluate unannotated raw images? 

Provided that the loader file is changed to not load the annotated.json, only load the image as numpy arrays and the --evaluate uses forward_evaluate() instead of evaluate() to output the results. 

Hence, if my goal is to just output some results that I do not need to compute the recall on, can I remove the loading of the annotated.json (categories, inverse weights, objects etc.) entirely and do as stated above? Thanks a lot!

**Comment by sometimething** [comment]
I also want to evaluate unannotated images to output some dection results.please let me know if you get the solution to this query. Thanks in advance.
