### ISSUE TITLE
env config

### ISSUE THREAD

**Issue by chuanzihe** [yikang-li/FactorizableNet#4]
what is your pytorch version? thank you.

**Comment by yikang-li** [comment]
Sorry for the missing. 

It's 0.3.0 

I may start migrating it to 0.4.0

Thanks for reminding.

Best,
Yikang

**Comment by chuanzihe** [comment]
thank you. looks to me most of the code works well under 0.4.0 (after some quick changes of APIs e.g. the volatile flag). 
just for reference: under **0.4.1**, the current lib/nms could have compile error, `nms_cuda.c:14:22: error: dereferencing pointer to incomplete type`. Probably due to the change of 0.4.1 [broadcast behavior](https://github.com/pytorch/pytorch/releases).

**Comment by yikang-li** [comment]
We have updated the project to support pytorch 1.0.1. However, it is just a beta version. You are welcome to have a try. 

Best,
Yikang

**Comment by emanuelazfernandes** [comment]
I can confirm that with a slight modification of pytorch 1.0.1 code ([here](https://github.com/pytorch/pytorch/blob/v1.0.1/torch/utils/cpp_extension.py#L398), directly in the conda/pip installed package, force the flag to `1`), I could successfully compile and run in Ubuntu 20.04, with CUDA 10.0.0-130, python 2.7, GCC 7, in a conda environment following the instructions in the README.

Keep in mind that the "old" methodology used here (legacy from the [faster-rcnn](https://github.com/longcw/faster_rcnn_pytorch) and [MSDN](https://github.com/yikang-li/MSDN) repos), which relies on compiling pytorch extensions in C, C++ and/or CUDA, the user *needs* to be extra careful between the version of CUDA installed locally and the one that was used to compile the pytorch package that normally users `conda install`.
