### ISSUE TITLE
How to run inference on my own image and show the result

### ISSUE THREAD

**Issue by xiaofeiwu** [yikang-li/FactorizableNet#6]
Would it be possible to provide a example code to run FNet on my own image and show the result?

**Comment by yikang-li** [comment]
Sorry, currently we haven't provided any guidance on running the inference on your own data. But it is not hard to do that. Please check the JSON file and prepare your own data in the similar version and modify ```lib/datasets/sVG_loader.py```  to make it fit for your own data. 

Actually, our core part of our inference model just uses the image as input. And you can draw the output as you want using opencv or matplotlib.
