### ISSUE TITLE
Wrong link for VRD dataset

### ISSUE THREAD

**Issue by xiaofeiwu** [yikang-li/FactorizableNet#7]
The link for VRD dataset seems to be unavailable: http://imagenet.stanford.edu/internal/jcjohns/scene_graphs/sg_dataset.zip

I'm not sure whether the link is wrong or other reasons.

**Comment by yikang-li** [comment]
It may be because the link is unavailable temporarily or forever. I may update the images we have later. Please ```star``` or ```watch``` our project for the updates. Thanks.

**Comment by emanuelazfernandes** [comment]
Here is a Google drive [link](https://drive.google.com/file/d/0Byvt-AfX75o1SVBTWFlPRGZGTXc/view?resourcekey=0-V3fW-908CLk30sxFVE9B-w).
