### ISSUE TITLE
Demo on own video

### ISSUE THREAD

**Issue by sophia-wright-blue** [yikang-li/FactorizableNet#8]
Thank you for releasing this repo. Would it be possible to use this model to do a demo on my own video (not just an image)? If yes, what would the steps be?

Thank you,

**Comment by yikang-li** [comment]
Sorry, currently, we just have the dataloader for the existing dataset. If you want to use it first a video: 1. write the data loading part; 2. fed the data into the pretrained model; 3. visualize the scene graph in videos

Unfortunately, now we just support the second step. We partly have the third step, but it just output the pdf graph.

**Comment by sophia-wright-blue** [comment]
thank you for replying @yikang-li , i'm gonna look into step 1 and 3.

**Comment by PRYUS** [comment]
Hey @sophia-wright-blue ! Have you been able to run it on your own video?

**Comment by sophia-wright-blue** [comment]
Hi @PRYUS , I had to move on to a different project and did not get to work on this one, good luck!
